apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
  name: hello-gitops-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gitops
      version: v2
  template:
    metadata:
      labels:
        app: hello-gitops
        version: v2
    spec:
      containers:
        - image: hello-gitops
          name: hello-gitops
          ports:
            - name: http
              containerPort: 8050
          env:
            - name: VERSION
              value: v2
