apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitopss
  name: hello-gitops-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gitops
      version: v1
  template:
    metadata:
      labels:
        app: hello-gitops
        version: v1
    spec:
      containers:
        - image: hello-gitops
          name: hello-gitops
          platform: linux/amd64
          ports:
            - name: http
              containerPort: 8050
          env:
            - name: VERSION
              value: v1
